# Generated by Django 5.0.7 on 2024-07-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/images')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.PositiveIntegerField(null=True)),
                ('otp_limit', models.IntegerField(null=True)),
                ('otp_delay', models.TimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('is_blocked', models.BooleanField(default=False, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type', models.CharField(choices=[('tutor', 'Tutor'), ('tutee', 'Tutee')], default='tutee', max_length=5)),
                ('password', models.CharField(db_index=True, default=None, max_length=200)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
                ('users_messaging_container', models.ManyToManyField(to='core_accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
