# Generated by Django 5.0.7 on 2024-07-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0004_alter_user__id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
