# Generated by Django 5.0.7 on 2024-07-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0005_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='profile_url',
        ),
    ]
